version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: dreamlabs_challenge
      POSTGRES_PASSWORD: dreamlabs_challenge_password
      POSTGRES_DB: dreamlabs_challenge
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
