export enum InvoiceEvents {
  INVOICE_CREATED = 'INVOICE_CREATED',
  INVOICE_UPDATED = 'INVOICE_UPDATED',
  INVOICE_PAID = 'INVOICE_PAID',
  INVOICE_UNPAID = 'INVOICE_UNPAID',
  INVOICE_REVERSED = 'INVOICE_REVERSED',
}
